name: CI Nightly Coverage

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: {}

jobs:
  coverage:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        run: pipx install uv
      - name: Install deps
        run: uv pip install -e .[dev]
      - name: Run full tests with coverage (lower gate initially)
        env:
          PYTEST_ADDOPTS: "--cov-fail-under=50"
        run: |
          pytest --cov=src --cov-report=term-missing
